
DATASET:
  DATASET_DIR: 'datasets'
  DATASET_NAME: 'License-Plate-Recognition-8'
  ANNOTATION_FILE_NAME: '_annotations.csv'
  BONE_FRACTURE_DETECTION_DATASET_URL: 'https://universe.roboflow.com/roboflow-universe-projects/license-plate-recognition-rxg4e/dataset/8#'

DATASET_DIRS:
  TRAIN_DIR: ${DATASET.DATASET_DIR}/${DATASET.DATASET_NAME}/train/
  VALIDATION_DIR: ${DATASET.DATASET_DIR}/${DATASET.DATASET_NAME}/valid
  TEST_DIR: ${DATASET.DATASET_DIR}/${DATASET.DATASET_NAME}/test


PRETRAIN_MODEL:
  MODEL_NAME: 'ssd_resnet50_v1_fpn_640x640_coco17_tpu-8'
  PATH: 'pre-trained-models/${PRETRAIN_MODEL.MODEL_NAME}'

TRAIN:
  BATCH_SIZE: 16
  NUM_EPOCHS: 10
  LEARNING_RATE: 0.0001
  IMG_SIZE: 224

OUTPUTS:
  OUPUT_DIR: 'exported_models/my_${PRETRAIN_MODEL.MODEL_NAME}'
  EXPORTER_SCRIPT: '/opt/models/research/object_detection/exporter_main_v2.py'
  CONFIG_PIPELINE_PATH: ${OUTPUTS.OUPUT_DIR}/
  CHECKPOINT_PATH: ${OUTPUTS.OUPUT_DIR}/checkpoints/

